export default [
    { label: "Ariston Electric Water Heater", value: "ariston-electric-water-heater" },
    { label: "Crane Bronze Gate Valve", value: "crane-bronze-gate-valve" },
    { label: "Crane Variable Orifice Double Regulating Valve", value: "crane-variable-orifice-double-regulating-valve" },
    { label: "Crane Bronze Strainer", value: "crane-bronze-strainer" },
    { label: "Crane Butterfly Valve", value: "crane-butterfly-valve" },
    { label: "DeWalt SDS Plus Hammer", value: "dewalt-sds-plus-hammer" },
    { label: "DeWalt Drill Driver", value: "dewalt-drill-driver" },
    { label: "DeWalt Hammer Drill Driver", value: "dewalt-hammer-drill-driver" },
    { label: "DeWalt SDS Plus Cordless Hammer", value: "dewalt-sds-plus-cordless-hammer" },
    { label: "DeWalt Percussion Drill", value: "dewalt-percussion-drill" },
    { label: "DeWalt Angle Grinder", value: "dewalt-angle-grinder" },
    { label: "Submersible Motor for Borewell Pumps", value: "submersible-motor-for-borewell-pumps" },
    { label: "Under the Sink RO System", value: "under-the-sink-ro-system" },
    { label: "Pressure Vessel", value: "pressure-vessel" },
    { label: "Anti Scaling System", value: "anti-scaling-system" },
    { label: "Booster Pump", value: "booster-pump" },
    { label: "Horizontal Multistage Centrifugal Pump", value: "horizontal-multistage-centrifugal-pump" },
    { label: "Inline Circulator Pump", value: "inline-circulator-pump" },
];